ELE_MODEL: # element recognition model -- logo only
  DETECTOR_TYPE: rfdetr  # rcnn | rfdetr
  CFG_PATH: models/faster_rcnn.yaml # used when DETECTOR_TYPE=rcnn
  WEIGHTS_PATH: models/rcnn_bet365.pth   # used when DETECTOR_TYPE=rcnn
  DETECT_THRE: 0.05
  # RF-DETR specific (used when DETECTOR_TYPE=rfdetr)
  RFD_WEIGHTS_PATH: test_weights.pt
  RFD_THRESHOLD: 0.35
  RFD_RESOLUTION: 512

SIAMESE_MODEL:
  NUM_CLASSES: 277 # number of brands, users don't need to modify this even the targetlist is expanded
  MATCH_THRE: 0.87 # FIXME: lowered from 0.87 to improve recall
  WEIGHTS_PATH: models/resnetv2_rgb_new.pth.tar
  TARGETLIST_PATH: models/expand_targetlist.zip
  DOMAIN_MAP_PATH: models/domain_map.pkl